import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { test } from "node:test";
import {
  executeAuthorizedRichPublication,
  stageRichPublication,
} from "../src/rich-publication.mjs";

const REVISION = "11111111-1111-4111-8111-111111111111";
const BLOCK_A = "22222222-2222-4222-8222-222222222222";
const BLOCK_B = "33333333-3333-4333-8333-333333333333";
const OBJECT = "44444444-4444-4444-8444-444444444444";
const BINDING = "55555555-5555-4555-8555-555555555555";
const ATTEMPT = "66666666-6666-4666-8666-666666666666";
const image = Buffer.from("original synthetic image bytes");
const digest = createHash("sha256").update(image).digest("hex");
function fixture() {
  const attrs = {
    object_id: OBJECT,
    object_version: 7,
    sha256: digest,
    alt: "first alternative",
    caption: "first caption",
  };
  const item = {
    binding_id: BINDING,
    object: {
      object_id: OBJECT,
      object_version: 7,
      sha256: digest,
    },
    media_type: "image/png",
    byte_len: image.byteLength,
    width: 8,
    height: 8,
    alt: attrs.alt,
    caption: attrs.caption,
    role: "image",
  };
  const payload = {
    schema_version: 2,
    format: "rich_markdown.v2",
    content_revision_id: REVISION,
    policy_version: "deterministic-rich-markdown-v2",
    document: {
      title: "Synthetic title",
      blocks: [
        {
          block_id: BLOCK_A,
          kind: "rich",
          text: "",
          citation_ids: [],
          items: [],
          rich: { version: 1, node: { type: "media", attrs } },
        },
        {
          block_id: BLOCK_B,
          kind: "rich",
          text: "",
          citation_ids: [],
          items: [],
          rich: {
            version: 1,
            node: {
              type: "media",
              attrs: {
                ...attrs,
                alt: "second alternative",
                caption: "second caption",
              },
            },
          },
        },
      ],
      schema_version: 2,
    },
    media: [
      item,
      {
        ...item,
        alt: "second alternative",
        caption: "second caption",
      },
    ],
  };
  const parts = [
    {
      ...item.object,
      media_type: item.media_type,
      bytes: Buffer.from(image),
    },
  ];
  return { payload, parts };
}

function canonical(value) {
  if (Array.isArray(value))
    return `[${value.map((element) => canonical(element)).join(",")}]`;
  if (value && typeof value === "object")
    return `{${Object.keys(value)
      .sort()
      .map((key) => `${JSON.stringify(key)}:${canonical(value[key])}`)
      .join(",")}}`;
  return JSON.stringify(value);
}

function variantFor(payload) {
  const title = payload.document.title;
  const markdown = "Frozen synthetic Markdown";
  const hash = createHash("sha256");
  for (const part of [
    "rich-publication-payload-v2",
    title,
    markdown,
    canonical(payload),
  ]) {
    const bytes = Buffer.from(part);
    const size = Buffer.alloc(8);
    size.writeBigUInt64BE(BigInt(bytes.length));
    hash.update(size).update(bytes);
  }
  return { title, markdown, payload_hash: hash.digest("hex") };
}

function stage(payload, parts, variant = variantFor(payload)) {
  return stageRichPublication(payload, parts, variant);
}

test("Rust empty paragraphs remain valid without changing their frozen encoding", () => {
  for (const node of [
    { type: "paragraph" },
    {
      type: "table",
      content: [
        {
          type: "tableRow",
          content: [{ type: "tableCell", content: [{ type: "paragraph" }] }],
        },
      ],
    },
  ]) {
    const { payload } = fixture();
    payload.document.blocks = [
      {
        block_id: BLOCK_A,
        kind: "rich",
        text: "",
        citation_ids: [],
        items: [],
        rich: { version: 1, node },
      },
    ];
    payload.media = [];
    const before = JSON.stringify(payload);
    assert.doesNotThrow(() => stage(payload, []));
    assert.equal(JSON.stringify(payload), before);
  }
  const { payload } = fixture();
  payload.document.blocks[0].rich.node = { type: "paragraph", content: null };
  assert.throws(() => stage(payload, []), /invalid_rich_payload/);
});

test("Rust and runner derive identical canonical structured and variant hashes", () => {
  // Generated by the Rust domain's rich_content golden test; unlike the byte
  // staging fixtures, this checks cross-language serialization exactly.
  const object = {
    object_id: "00000000-0000-0000-0000-000000000015",
    object_version: 1,
    sha256: "a".repeat(64),
  };
  const payload = {
    schema_version: 2,
    format: "rich_markdown.v2",
    content_revision_id: "00000000-0000-0000-0000-000000000001",
    policy_version: "deterministic-rich-markdown-v2",
    document: {
      title: "A <title>",
      blocks: [
        {
          block_id: "00000000-0000-0000-0000-000000000000",
          kind: "rich",
          text: "",
          citation_ids: [],
          items: [],
          rich: {
            version: 1,
            node: {
              type: "media",
              attrs: {
                ...object,
                alt: "Detail",
                caption: "Image one",
              },
            },
          },
        },
      ],
      schema_version: 2,
    },
    media: [
      {
        binding_id: "00000000-0000-0000-0000-00000000000e",
        object,
        media_type: "image/png",
        byte_len: 160,
        width: 8,
        height: 7,
        alt: "Detail",
        caption: "Image one",
        role: "image",
      },
    ],
  };
  assert.equal(
    createHash("sha256").update(canonical(payload)).digest("hex"),
    "8a715d3f4176af43d5c3377764c0371985755bdac71dd96be901e6bd4316016e",
  );
  const title = payload.document.title;
  const markdown =
    "# A &lt;title\\>\n\n![Detail](media/00000000-0000-0000-0000-000000000015-1)\n\nImage one";
  const hash = createHash("sha256");
  for (const part of [
    "rich-publication-payload-v2",
    title,
    markdown,
    canonical(payload),
  ]) {
    const bytes = Buffer.from(part, "utf8");
    const length = Buffer.alloc(8);
    length.writeBigUInt64BE(BigInt(bytes.byteLength));
    hash.update(length).update(bytes);
  }
  assert.equal(
    hash.digest("hex"),
    "79ea2c42c4bfec9550ef7356c9a475686941bad1f8c676520e5577007d7f4874",
  );
});

const expected = {
  attempt_id: ATTEMPT,
  runner_session_id: "session-1",
  payload_hash: variantFor(fixture().payload).payload_hash,
};

const grant = () => ({
  status: "granted",
  ...expected,
  send_not_after: "2030-01-01T00:00:00Z",
});
const code = (value) => value?.code;

test("frozen document retains every occurrence while bytes are staged once", async () => {
  const { payload, parts } = fixture();
  const stage = stageRichPublication(payload, parts, variantFor(payload));
  assert.equal(stage.payload.media.length, 2);
  assert.equal(stage.media.length, 1);
  assert.equal(
    Object.isFrozen(stage.payload.document.blocks[0].rich.node.attrs),
    true,
  );
  assert.equal(
    JSON.stringify(stage).includes("original synthetic image"),
    false,
  );
  parts[0].bytes.fill(0);
  payload.media[0].alt = "mutated";
  let authorizations = 0;
  const result = await executeAuthorizedRichPublication(stage, {
    expected,
    authorize: () => {
      authorizations++;
      return grant();
    },
    upload: (document, media) => {
      assert.equal(document.media[0].alt, "first alternative");
      assert.equal(document.media[1].alt, "second alternative");
      assert.equal(media.length, 1);
      assert.equal(
        createHash("sha256").update(media[0].bytes).digest("hex"),
        digest,
      );
      return "uploaded-test-only";
    },
    clock: () => Date.parse("2029-01-01T00:00:00Z"),
  });
  assert.equal(result, "uploaded-test-only");
  assert.equal(authorizations, 1);
  await assert.rejects(
    executeAuthorizedRichPublication(stage, {
      expected,
      authorize: grant,
      upload: () => {},
    }),
    (error) => code(error) === "rich_stage_consumed",
  );
});

test("staging rejects corrupted, missing, substituted and duplicated byte parts", () => {
  const { payload, parts } = fixture();
  assert.throws(
    () => stage(payload, [{ ...parts[0], bytes: Buffer.from(image).fill(0) }]),
    (error) => code(error) === "media_bytes_corrupt",
  );
  assert.throws(
    () => stage(payload, []),
    (error) => code(error) === "media_parts_mismatch",
  );
  assert.throws(
    () => stage(payload, [{ ...parts[0], object_version: 8 }]),
    (error) => code(error) === "media_parts_mismatch",
  );
  assert.throws(
    () => stage(payload, [...parts, ...parts]),
    (error) => code(error) === "media_parts_mismatch",
  );
  assert.throws(
    () => stage(payload, [{ ...parts[0], media_type: "image/webp" }]),
    (error) => code(error) === "media_parts_mismatch",
  );
});

test("manifest reorder, changed occurrence and conflicting duplicate object fail closed", () => {
  const changed = fixture();
  changed.payload.media.reverse();
  assert.throws(
    () => stage(changed.payload, changed.parts),
    (error) => code(error) === "media_manifest_mismatch",
  );
  const changedAlt = fixture();
  changedAlt.payload.media[0].alt = "substituted";
  assert.throws(
    () => stage(changedAlt.payload, changedAlt.parts),
    (error) => code(error) === "media_manifest_mismatch",
  );
  const duplicateConflict = fixture();
  duplicateConflict.payload.media[1].binding_id = REVISION;
  assert.throws(
    () => stage(duplicateConflict.payload, duplicateConflict.parts),
    (error) => code(error) === "media_identity_conflict",
  );
});

test("unsupported structure and hostile media/address fields reject before authorization", () => {
  const wrong = fixture();
  wrong.payload.document.blocks[0].rich.node = {
    type: "unsupportedEmbed",
    attrs: { src: "https://content.invalid/image" },
  };
  assert.throws(
    () => stage(wrong.payload, wrong.parts),
    (error) => code(error) === "unsupported_rich_node",
  );
  const address = fixture();
  address.payload.media[0].url = "https://content.invalid/image";
  assert.throws(
    () => stage(address.payload, address.parts),
    (error) => code(error) === "invalid_rich_payload",
  );
});

test("frozen variant hash binds revision, order and media captions before staging", () => {
  const { payload, parts } = fixture();
  assert.throws(
    () =>
      stage(payload, parts, {
        ...variantFor(payload),
        payload_hash: "b".repeat(64),
      }),
    (error) => code(error) === "rich_payload_hash_mismatch",
  );
  const frozen = variantFor(payload);
  payload.media[1].caption = "different caption";
  payload.document.blocks[1].rich.node.attrs.caption = "different caption";
  assert.throws(
    () => stage(payload, parts, frozen),
    (error) => code(error) === "rich_payload_hash_mismatch",
  );
  const other = fixture();
  other.payload.content_revision_id = BLOCK_A;
  assert.throws(
    () => stage(other.payload, other.parts, variantFor(fixture().payload)),
    (error) => code(error) === "rich_payload_hash_mismatch",
  );
});

test("denied, lost and replayed grants never call external adapter", async () => {
  for (const [authorize, expectedCode] of [
    [() => ({ status: "denied" }), "send_authorization_denied"],
    [() => ({ status: "already_consumed" }), "send_authorization_consumed"],
    [
      () => Promise.reject(new Error("secret: do not log")),
      "send_authorization_unknown",
    ],
    [
      () => ({ ...grant(), attempt_id: REVISION }),
      "send_authorization_unknown",
    ],
    [
      () => ({ ...grant(), runner_session_id: "other" }),
      "send_authorization_unknown",
    ],
    [
      () => ({ ...grant(), payload_hash: "b".repeat(64) }),
      "send_authorization_unknown",
    ],
  ]) {
    const { payload, parts } = fixture();
    const stage = stageRichPublication(payload, parts, variantFor(payload));
    let uploads = 0;
    await assert.rejects(
      executeAuthorizedRichPublication(stage, {
        expected,
        authorize,
        upload: () => uploads++,
        clock: () => Date.parse("2029-01-01T00:00:00Z"),
      }),
      (error) =>
        code(error) === expectedCode && !error.message.includes("secret"),
    );
    assert.equal(uploads, 0);
  }
});

test("expiry rechecks immediately before first external action and no replay", async () => {
  const { payload, parts } = fixture();
  const stage = stageRichPublication(payload, parts, variantFor(payload));
  let uploads = 0;
  await assert.rejects(
    executeAuthorizedRichPublication(stage, {
      expected,
      authorize: grant,
      upload: () => uploads++,
      clock: () => Date.parse("2030-01-01T00:00:00Z"),
    }),
    (error) => code(error) === "send_authorization_expired",
  );
  assert.equal(uploads, 0);
  await assert.rejects(
    executeAuthorizedRichPublication(stage, {
      expected,
      authorize: grant,
      upload: () => uploads++,
    }),
    (error) => code(error) === "rich_stage_consumed",
  );
});

test("invalid clock cannot bypass send grant expiry", async () => {
  const { payload, parts } = fixture();
  const frozen = stage(payload, parts);
  let uploads = 0;
  await assert.rejects(
    executeAuthorizedRichPublication(frozen, {
      expected,
      authorize: grant,
      upload: () => uploads++,
      clock: () => Number.NaN,
    }),
    (error) => code(error) === "send_authorization_expired",
  );
  assert.equal(uploads, 0);
});

test("ambiguous authorization timeout consumes the stage without upload", async () => {
  const { payload, parts } = fixture();
  const stage = stageRichPublication(payload, parts, variantFor(payload));
  let resolveAuthorization;
  const pending = new Promise((resolve) => {
    resolveAuthorization = resolve;
  });
  let uploads = 0;
  await assert.rejects(
    executeAuthorizedRichPublication(stage, {
      expected,
      authorize: () => pending,
      upload: () => uploads++,
      authorizationTimeoutMs: 5,
    }),
    (error) => code(error) === "send_authorization_unknown",
  );
  resolveAuthorization(grant());
  await Promise.resolve();
  assert.equal(uploads, 0);
  await assert.rejects(
    executeAuthorizedRichPublication(stage, {
      expected,
      authorize: grant,
      upload: () => uploads++,
    }),
    (error) => code(error) === "rich_stage_consumed",
  );
});

test("adapter ambiguity after a granted send cannot reuse stage or grant", async () => {
  const { payload, parts } = fixture();
  const frozen = stage(payload, parts);
  let authorizations = 0;
  let uploads = 0;
  await assert.rejects(
    executeAuthorizedRichPublication(frozen, {
      expected,
      authorize: () => {
        authorizations++;
        return grant();
      },
      upload: () => {
        uploads++;
        throw new Error("external outcome ambiguous");
      },
      clock: () => Date.parse("2029-01-01T00:00:00Z"),
    }),
    /external outcome ambiguous/u,
  );
  await assert.rejects(
    executeAuthorizedRichPublication(frozen, {
      expected,
      authorize: () => authorizations++,
      upload: () => uploads++,
    }),
    (error) => code(error) === "rich_stage_consumed",
  );
  assert.equal(authorizations, 1);
  assert.equal(uploads, 1);
});
